#!/usr/bin/env python3
"""Download national flags from flagcdn.com, decode + resize, emit as RGB565
arrays keyed by the 3-letter code the football-data API returns (`tla`), which
the firmware looks up directly. De-duplicated by flag image.
Run from project root:  python scripts/build_flags.py
"""
import io
import os
import urllib.request

from PIL import Image

# football-data `tla` (≈ FIFA code) -> flagcdn slug (ISO-3166 alpha-2 / gb-*).
# Comprehensive enough to cover any WC 2026 participant. Multiple codes may map
# to one slug (e.g. URU/URY) — images are de-duplicated below.
CODE_TO_SLUG = {
    # Europe
    "ALB": "al", "AUT": "at", "BEL": "be", "BUL": "bg", "BIH": "ba",
    "BLR": "by", "CRO": "hr", "CYP": "cy", "CZE": "cz", "DEN": "dk",
    "ENG": "gb-eng", "ESP": "es", "FIN": "fi", "FRA": "fr", "GEO": "ge",
    "GER": "de", "GRE": "gr", "HUN": "hu", "ISL": "is", "ITA": "it",
    "KOS": "xk", "LUX": "lu", "MKD": "mk", "MNE": "me", "NED": "nl",
    "NIR": "gb-nir", "NOR": "no", "POL": "pl", "POR": "pt", "IRL": "ie",
    "ROU": "ro", "RUS": "ru", "SCO": "gb-sct", "SRB": "rs", "SVK": "sk",
    "SVN": "si", "SWE": "se", "SUI": "ch", "TUR": "tr", "UKR": "ua",
    "WAL": "gb-wls",
    # South America
    "ARG": "ar", "BOL": "bo", "BRA": "br", "CHI": "cl", "COL": "co",
    "ECU": "ec", "PAR": "py", "PER": "pe", "URU": "uy", "URY": "uy",
    "VEN": "ve",
    # North / Central America & Caribbean
    "CAN": "ca", "CRC": "cr", "CUB": "cu", "CUW": "cw", "SLV": "sv",
    "GUA": "gt", "HAI": "ht", "HON": "hn", "JAM": "jm", "MEX": "mx",
    "PAN": "pa", "TRI": "tt", "USA": "us", "SUR": "sr", "NCA": "ni",
    # Africa
    "ALG": "dz", "ANG": "ao", "BFA": "bf", "BEN": "bj", "CMR": "cm",
    "CPV": "cv", "CIV": "ci", "COD": "cd", "CGO": "cg", "EGY": "eg",
    "EQG": "gq", "GAB": "ga", "GHA": "gh", "GUI": "gn", "KEN": "ke",
    "MLI": "ml", "MAR": "ma", "MOZ": "mz", "MTN": "mr", "NAM": "na",
    "NGA": "ng", "RSA": "za", "SEN": "sn", "TAN": "tz", "TOG": "tg",
    "TUN": "tn", "UGA": "ug", "ZAM": "zm", "ZIM": "zw", "MAD": "mg",
    "GAM": "gm",
    # Asia
    "AUS": "au", "BHR": "bh", "CHN": "cn", "TPE": "tw", "HKG": "hk",
    "IND": "in", "IDN": "id", "IRN": "ir", "IRQ": "iq", "JPN": "jp",
    "JOR": "jo", "KOR": "kr", "PRK": "kp", "KUW": "kw", "KGZ": "kg",
    "LBN": "lb", "MAS": "my", "OMN": "om", "PAK": "pk", "PLE": "ps",
    "QAT": "qa", "KSA": "sa", "SGP": "sg", "SYR": "sy", "THA": "th",
    "TJK": "tj", "TKM": "tm", "UAE": "ae", "UZB": "uz", "VIE": "vn",
    "YEM": "ye",
    # Oceania
    "NZL": "nz", "NCL": "nc", "FIJ": "fj", "SOL": "sb", "TAH": "pf",
    "VAN": "vu", "PNG": "pg",
}

FW, FH = 30, 20
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
H_PATH = os.path.join(ROOT, "include", "assets", "flags.h")
C_PATH = os.path.join(ROOT, "src", "assets", "flags.cpp")


def fetch_rgb565(slug):
    url = f"https://flagcdn.com/w80/{slug}.png"
    req = urllib.request.Request(url, headers={"User-Agent": "wc-tracker"})
    with urllib.request.urlopen(req, timeout=20) as r:
        raw = r.read()
    img = Image.open(io.BytesIO(raw)).convert("RGB").resize((FW, FH), Image.LANCZOS)
    return [((r8 & 0xF8) << 8) | ((g8 & 0xFC) << 3) | (b8 >> 3)
            for (r8, g8, b8) in img.getdata()]


def ident(slug):
    return slug.replace("-", "_")


def main():
    os.makedirs(os.path.dirname(H_PATH), exist_ok=True)
    os.makedirs(os.path.dirname(C_PATH), exist_ok=True)

    slugs = sorted(set(CODE_TO_SLUG.values()))
    pixels = {}
    for slug in slugs:
        try:
            pixels[slug] = fetch_rgb565(slug)
        except Exception as e:  # noqa: BLE001
            print(f"  !! {slug} failed: {e}")
    print(f"  fetched {len(pixels)}/{len(slugs)} unique flags")

    codes = sorted(c for c, s in CODE_TO_SLUG.items() if s in pixels)

    with open(C_PATH, "w", newline="\n") as f:
        f.write('#include "assets/flags.h"\n\n#include <cstring>\n\n')
        f.write("// AUTO-GENERATED by scripts/build_flags.py — do not edit.\n")
        f.write(f"// {FW}x{FH} RGB565, source flagcdn.com, de-duplicated by image.\n\n")
        f.write("namespace assets {\n\n")
        for slug in sorted(pixels):
            f.write(f"static const uint16_t kPix_{ident(slug)}[] = {{\n")
            px = pixels[slug]
            for i in range(0, len(px), 12):
                f.write("  " + ", ".join(f"0x{v:04X}" for v in px[i:i + 12]) + ",\n")
            f.write("};\n\n")
        f.write("const Flag kFlags[] = {\n")
        for c in codes:
            f.write(f'  {{"{c}", kPix_{ident(CODE_TO_SLUG[c])}, {FW}, {FH}}},\n')
        f.write("};\n")
        f.write(f"const size_t kFlagCount = {len(codes)};\n\n")
        f.write(
            "const uint16_t* flagImage(const char* code, uint16_t* w, uint16_t* h) {\n"
            "  for (size_t i = 0; i < kFlagCount; ++i) {\n"
            "    if (strcmp(kFlags[i].code, code) == 0) {\n"
            "      if (w) *w = kFlags[i].w;\n"
            "      if (h) *h = kFlags[i].h;\n"
            "      return kFlags[i].data;\n"
            "    }\n"
            "  }\n"
            "  return nullptr;\n"
            "}\n\n"
            "}  // namespace assets\n"
        )

    with open(H_PATH, "w", newline="\n") as f:
        f.write(
            "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n"
            "// AUTO-GENERATED companion: see scripts/build_flags.py\n\n"
            "namespace assets {\n\n"
            "struct Flag { const char* code; const uint16_t* data; "
            "uint16_t w; uint16_t h; };\n"
            "extern const Flag kFlags[];\nextern const size_t kFlagCount;\n\n"
            "/** RGB565 flag for an API 3-letter code (w/h filled), or nullptr. */\n"
            "const uint16_t* flagImage(const char* code, uint16_t* w, uint16_t* h);\n\n"
            "}  // namespace assets\n"
        )
    print(f"\nWrote {len(codes)} codes / {len(pixels)} images ({FW}x{FH}) -> {C_PATH}")


if __name__ == "__main__":
    main()
